# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: zchatoua <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/04 08:53:46 by zchatoua          #+#    #+#              #
#    Updated: 2018/10/04 08:58:03 by zchatoua         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

TARGET = ft_display_file

all : $(TARGET)

$(TARGET) :
	@gcc -Wall -Werror -Wextra main.c -o $(TARGET)

clean :
	@rm -f *.o

fclean : clean
	@rm -f $(TARGET)
